package com.fulfilment.application.monolith.exceptions;

public enum ErrorRule {
    WAREHOUSE_NOT_FOUND,
    WAREHOUSE_ALREADY_ARCHIVED,
    INVALID_REPLACEMENT_BU_CODE,
    WAREHOUSE_STOCK_MISMATCH,
    LOCATION_CHANGE_NOT_ALLOWED,
    WAREHOUSE_CAPACITY_NOT_ENOUGH,
    WAREHOUSE_STOCK_EXCEEDS_CAPACITY,
    INVALID_LOCATION,
    LOCATION_MAX_WAREHOUSES_REACHED,
    LOCATION_CAPACITY_EXCEEDED
}
